### PR TITLE
Removed RTSA from Repo

### PR DESCRIPTION
**Pull request by mfarhan12**

### CODE REVIEW

**Comment by wardi** [comment]
docs + readme also need to be updated, screenshots removed.

this also doesn't merge cleanly, want me to merge #149 first?

**Comment by mfarhan12** [comment]
merge #149, ill update docs + readme,

**Comment by wardi** [comment]
Hmm. still not a clean merge, what are we missing?

**Comment by mfarhan12** [comment]
Should be good now, I think it was because I physically removed the GUI files

**Pull request merged**
